                                                                                                                                                                               
  CREATE TABLE CUSTOMERS                                                                                                                                                                   
   (	"CUSTOMER_ID" VARCHAR2(20),                                                                                                                                                                        
	"CUSTOMER_PHONE" NUMBER,                                                                                                                                                                               
	"FIRST_NAME" VARCHAR2(25),                                                                                                                                                                             
	"LAST_NAME" VARCHAR2(25),                                                                                                                                                                              
	PRIMARY KEY ("CUSTOMER_ID")  
    )                                                                                                                                                                       
                                                                                                                                                                                      
                                                                                                                                                                                                        
  CREATE TABLE FARMERS                                                                                                                                                                    
   (	"FARMER_ID" VARCHAR2(20),                                                                                                                                                                          
	"FARMER_PHONE" NUMBER,                                                                                                                                                                                 
	"FIRST_NAME" VARCHAR2(25),                                                                                                                                                                             
	"LAST_NAME" VARCHAR2(25),                                                                                                                                                                              
	 PRIMARY KEY ("FARMER_ID")                                                                                                                                                                             
   )                                                                                                                                                  
                                                                                                                                                                                                        
  CREATE TABLE GRAIN                                                                                                                                                                         
   (	"GRAIN_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,       
	"GRAIN_NAME" VARCHAR2(50),                                                                                                                                                                             
	 PRIMARY KEY ("GRAIN_ID")                                                                                                                                                                              
   )                                                                                                                                           
                                                                                                                                                                                                        
  CREATE TABLE LISTINGS                                                                                                                                                               
   (	"LISTING_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,     
	"FARMER_ID" VARCHAR2(20),                                                                                                                                                                              
	"GRAIN_ID" NUMBER,                                                                                                                                                                                     
	"QUANTITY_AVAILABLE" NUMBER,                                                                                                                                                                           
	"PRICE_PER_UNIT" NUMBER(10,2),                                                                                                                                                                         
	"DATE_POSTED" DATE DEFAULT SYSDATE,                                                                                                                                                                    
	"STATUS" VARCHAR2(20) DEFAULT 'active',                                                                                                                                                                
	 CHECK (quantity_available >= 0) ENABLE,                                                                                                                                                               
	 PRIMARY KEY ("LISTING_ID")                                                                                                                                                                            
                                                                                                                                                                       
   )                                                                                                                                                                       
                                                                                                                                                                                                        
  CREATE TABLE TRANSACTION                                                                                                                                                                 
   ("TRANSACTION_ID" NUMBER,                                                                                                                                                                           
	"TRANS_DATE" DATE,                                                                                                                                                                                     
	"FARMER_ID" VARCHAR2(20),                                                                                                                                                                              
	"CUSTOMER_ID" VARCHAR2(20),                                                                                                                                                                            
	"GRAIN_ID" NUMBER,                                                                                                                                                                                     
	"QUANTITY" NUMBER,                                                                                                                                                                                     
	"PRICE_PER_UNIT" NUMBER(10,2),                                                                                                                                                                         
	PRIMARY KEY ("TRANSACTION_ID")                                                                                                                                                                        
                                                                                                                                                       
   )                                                                                                                                                                                  
                                                                                                                                                                                                        
  CREATE TABLE TRANSACTION_DETAILS                                                                                                                                                           
   (	"TRANSACTION_ID" NUMBER,                                                                                                                                                                           
	"TRANS_DATE" DATE,                                                                                                                                                                                     
	"FARMER_ID" VARCHAR2(20),                                                                                                                                                                              
	"FARMER_NAME" VARCHAR2(50),                                                                                                                                                                            
	"FARMER_PHONE" NUMBER,                                                                                                                                                                                 
	"CUSTOMER_ID" VARCHAR2(20),                                                                                                                                                                            
	"CUSTOMER_NAME" VARCHAR2(50),                                                                                                                                                                          
	"CUSTOMER_PHONE" NUMBER,                                                                                                                                                                               
	"GRAIN_NAME" VARCHAR2(50),                                                                                                                                                                             
	"QUANTITY" NUMBER,                                                                                                                                                                                     
	"PRICE_PER_UNIT" NUMBER(10,2),                                                                                                                                                                         
	CONSTRAINT "PK_TRANSACTION" PRIMARY KEY ("TRANSACTION_ID")                                                                                     
   )